name: Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  schedule:
    - cron: '18 7 3 * *'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: ''
      CARGO_PROFILE_DEV_DEBUG: '0' # reduce size of target directory

    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - name: Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
