name: Test

on:
  push:
  pull_request:
    branches:
      - main
      - master
  schedule:
    - cron: '18 7 3 * *'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: ''
      CARGO_PROFILE_DEV_DEBUG: '0' # reduce size of target directory

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
